
package todo_soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ToDoWebService", targetNamespace = "http://toDo_SOAP/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDoWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeToDo", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.RemoveToDo")
    @ResponseWrapper(localName = "removeToDoResponse", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.RemoveToDoResponse")
    public String removeToDo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addToDo", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.AddToDo")
    @ResponseWrapper(localName = "addToDoResponse", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.AddToDoResponse")
    public String addToDo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @return
     *     returns java.util.List<todo_soap.ToDo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listToDo", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.ListToDo")
    @ResponseWrapper(localName = "listToDoResponse", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.ListToDoResponse")
    public List<ToDo> listToDo();

}
